server:
  port: 8882
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          #git的仓库地址
          uri: http://192.168.86.133/springcloud/my-config-project.git
          #git的用户名
          username: root
          #git的密码
          password: 123456@root
      #指定分支
      label: master

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/